#
# Quarkus
#
quarkus.banner.enabled = false
quarkus.ssl.native=true
## testing ##
quarkus.test.integration-test-profile=dev
quarkus.test.native-image-profile=dev

## Kafka
%prod.kafka.brokers=kafka:29092
%prod.kafka.clientId=ms-camel-quarkus-kafka
%prod.quarkus.kafka.devservices.enabled=false

%dev.quarkus.devservices.enabled=false
%dev.quarkus.kafka.devservices.enabled=false
%dev.kafka.brokers=localhost:9092
%dev.kafka.clientId=ms-camel-quarkus-kafka

#by default quarkus.kafka.devservices.enabled = true. we need to add devservices.provider
%test.quarkus.kafka.devservices.enabled=true
%test.kafka.brokers=localhost:9092
%test.quarkus.kafka.devservices.provider=kafka-native
%test.quarkus.kafka.devservices.port=9092
%test.quarkus.kafka.devservices.topic-partitions.my-topic=1

## testing ##

# Kubernetes Config
 %prod.quarkus.kubernetes-config.enabled=true
 %test,dev.quarkus.kubernetes-config.enabled=false

 %prod.quarkus.kubernetes-config.secrets.enabled=true
 %test,dev.quarkus.kubernetes-config.secrets.enabled=false

 %prod.quarkus.kubernetes-config.config-maps=ms-k8s-cml-qks-kafka-configmap
 %prod.quarkus.kubernetes-config.secrets=ms-k8s-cml-qks-kafka-secret

#
# Ports
quarkus.http.test-port=9000
quarkus.http.port=9000
quarkus.http.ssl-port=9020

#Propery
%test,dev.log.message=log message from properties