#
# Quarkus
#
quarkus.banner.enabled = false
quarkus.ssl.native=true
## testing ##
quarkus.test.integration-test-profile=dev
quarkus.test.native-image-profile=dev

## Kafka
kafka.host=127.0.0.1
kafka.port=9092

#by default quarkus.kafka.devservices.enabled = true. we neet to add devservices.provider
%test,dev.quarkus.kafka.devservices.enabled=true
%test,dev.quarkus.kafka.devservices.provider=kafka-native
%test,dev.quarkus.kafka.devservices.port=9092
%test,dev.quarkus.kafka.devservices.topic-partitions.my-topic=1

%prod.quarkus.kafka.devservices.enabled=false

## testing ##

# Kubernetes Config
 %prod.quarkus.kubernetes-config.enabled=true
 %test,dev.quarkus.kubernetes-config.enabled=false

 %prod.quarkus.kubernetes-config.secrets.enabled=true
 %test,dev.quarkus.kubernetes-config.secrets.enabled=false

 %prod.quarkus.kubernetes-config.config-maps=ms-quarkus-kafka-v1-configmap
 %prod.quarkus.kubernetes-config.secrets=ms-quarkus-kafka-v1-secrets

#
# Ports
quarkus.http.test-port=9000
quarkus.http.port=9000
quarkus.http.ssl-port=9020