openapi: 3.0.1
info:
  title: secretExample_v1_reader_api
  description: API Definition of secretExample_v1_reader_api
  version: 1.0.0
servers:
- url: http://localhost:8290/reader
paths:
  /secret:
    get:
      responses:
        default:
          description: Default response
