
package es.home.ws.example.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.home.ws.example.ObjectFactory;
import es.home.ws.example.Saludo;
import es.home.ws.example.UserXml;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSample", targetNamespace = "http://example.ws.home.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSample {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "despide", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.Despide")
    @ResponseWrapper(localName = "despideResponse", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.DespideResponse")
    @Action(input = "http://example.ws.home.es/WebServiceSample/despideRequest", output = "http://example.ws.home.es/WebServiceSample/despideResponse")
    public String despide();

    /**
     * 
     * @return
     *     returns es.home.ws.example.Saludo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saluda", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.Saluda")
    @ResponseWrapper(localName = "saludaResponse", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.SaludaResponse")
    @Action(input = "http://example.ws.home.es/WebServiceSample/saludaRequest", output = "http://example.ws.home.es/WebServiceSample/saludaResponse")
    public Saludo saluda();

    /**
     * 
     * @return
     *     returns java.util.List<es.home.ws.example.UserXml>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://example.ws.home.es/", className = "es.home.ws.example.GetUsersResponse")
    @Action(input = "http://example.ws.home.es/WebServiceSample/getUsersRequest", output = "http://example.ws.home.es/WebServiceSample/getUsersResponse")
    public List<UserXml> getUsers();

}
