
package es.home.ws.example.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceSampleImplService", targetNamespace = "http://impl.example.ws.home.es/", wsdlLocation = "file:/home/ubuntu/Documents/GitHub/PostExamples/ExampleWSClient/src/main/resources/META-INF/wsdl/webservice-sample.wsdl")
public class WebServiceSampleImplService
    extends Service
{

    private final static URL WEBSERVICESAMPLEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESAMPLEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICESAMPLEIMPLSERVICE_QNAME = new QName("http://impl.example.ws.home.es/", "WebServiceSampleImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/ubuntu/Documents/GitHub/PostExamples/ExampleWSClient/src/main/resources/META-INF/wsdl/webservice-sample.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESAMPLEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICESAMPLEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceSampleImplService() {
        super(__getWsdlLocation(), WEBSERVICESAMPLEIMPLSERVICE_QNAME);
    }

    public WebServiceSampleImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESAMPLEIMPLSERVICE_QNAME, features);
    }

    public WebServiceSampleImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESAMPLEIMPLSERVICE_QNAME);
    }

    public WebServiceSampleImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESAMPLEIMPLSERVICE_QNAME, features);
    }

    public WebServiceSampleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSampleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "WebServiceSampleImplPort")
    public WebServiceSample getWebServiceSampleImplPort() {
        return super.getPort(new QName("http://impl.example.ws.home.es/", "WebServiceSampleImplPort"), WebServiceSample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSample
     */
    @WebEndpoint(name = "WebServiceSampleImplPort")
    public WebServiceSample getWebServiceSampleImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.example.ws.home.es/", "WebServiceSampleImplPort"), WebServiceSample.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESAMPLEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESAMPLEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICESAMPLEIMPLSERVICE_WSDL_LOCATION;
    }

}
