CREATE TABLE `user_roles` (
  `USER_ROLE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) DEFAULT NULL,
  `AUTHORITY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  UNIQUE KEY `USER_ROLE_ID_UNIQUE` (`USER_ROLE_ID`),
  KEY `FK_user_roles` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

CREATE TABLE `users` (
  `USER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_LOCKED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_EXPIRED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_CREDENTIAL_EXPIRED` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

#user:admin password:admin
insert into users (USER_ID, USERNAME, PASSWORD, ENABLED, NON_LOCKED, NON_EXPIRED, NON_CREDENTIAL_EXPIRED) values ('1', 'admin', '$2a$10$h.p9sfywxm02e0tU8Zlu2O5VEb6JFOUU6V5RhdVhxIvOeduMppMvS', '1', '1', '1', '1');

insert into user_roles (USER_ROLE_ID, USER_ID, AUTHORITY) values ('1', '1', 'ROLE_ADMIN') ;

